[package]
name = "apebdlm"
version = "0.0.1"
edition = "2021"
license = "BSD-3-Clause"
keywords = ["macros", "file io", "binary data"]
catagories = ["development-tools"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
